### ISSUE TITLE
Admin & Seller password

### ISSUE THREAD

**Issue by YagneshBrahmbhatt** [AMB-19/SuperMarketManagementSystem#1]
Hi there, can you provide me the admin and seller password, or can you tell me where to find it?

**Comment by ahmedmbutt** [comment]
Admin ID: **Group1**
Password: **Project**
https://github.com/ahmedmbutt/SuperMarketManagementSystem/blob/13f6e069ae83c8fae6409a5f321dceddd99bbb0b/src/supermarket/Login.java#L272

**Comment by YagneshBrahmbhatt** [comment]
Thankyou so much.

**Comment by oiunl** [comment]
Hey, I am unable to find the executable jar file in the dist folder once I download it. I did clean and built and created a jar file but its not not happening.

**Comment by ahmedmbutt** [comment]
See if you can find a solution here: [How to make an executable JAR file?](https://stackoverflow.com/questions/5258159/how-to-make-an-executable-jar-file)
