### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by oiunl** [AMB-19/SuperMarketManagementSystem#4]
I am unable able to login as seller, kindly provide the username and password of seller. 

The app is really nice, thank you so much!!!

**Comment by oiunl** [comment]
I am unable able to login as seller, kindly provide the username and password of seller.

The app is really nice, thank you so much!!!

**Comment by ahmedmbutt** [comment]
You must first log in as an admin and create seller accounts, after which you can log in as a seller. The accounts of sellers are stored in the seller.txt file.

The credentials for admin account are as follows:
```
Admin ID: Group1
Password: Project
```

**Comment by oiunl** [comment]
I logged in as admin and created seller accounts but when I go back and trying loggin in as seller the program doesn'r run anymore. It is because I changed the desgin of the page a bit?

**Comment by ahmedmbutt** [comment]
Consider re-cloning the project and adding seller accounts prior to modifying the design. Additionally, verify the seller.txt file to ensure that the sellers are being added correctly.

**Comment by ahmedmbutt** [comment]
Consider re-cloning the project and adding seller accounts prior to modifying the design. Additionally, verify the seller.txt file to ensure that the sellers are being added correctly.

**Comment by oiunl** [comment]
Heyy, I figured it out. I had to intialize the ID and Password and it worked. Thank you sm!
